import os
from typing import Any

from google import genai
from google.genai import types

from .base import GenerationResult, ImageGenerationProvider


class GeminiProvider(ImageGenerationProvider):
    """
    Gemini API (Google GenAI) を利用して画像を生成するプロバイダー。
    """

    def __init__(self) -> None:
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            # 開発用フォールバックか、エラーにする
            # ここでは client 作成を遅延させるか、環境変数がない場合は None にする
            self.client = None
        else:
            self.client = genai.Client(api_key=api_key)

    @property
    def name(self) -> str:
        return "Gemini API"

    async def get_status(self) -> dict:
        return {
            "connected": self.client is not None,
            "provider": self.name,
            "model": "imagen-3.0-generate-001",
        }

    async def generate(
        self,
        prompt: str,
        *,
        width: int = 512,
        height: int = 512,
        **params: Any,
    ) -> GenerationResult:
        
        req_api_key = params.get("api_key")
        
        if req_api_key:
            client = genai.Client(api_key=req_api_key)
        else:
            client = self.client
            
        if not client:
            raise RuntimeError("GEMINI_API_KEY is not set. Please set it in Settings.")

        # Note: GenAI API の generate_images は現在 txt2img のみ対応 (画像入力は未対応)
        # ユーザーから渡されたコンポジット画像 (image_bytes) はここでは使用せず、
        # プロンプトをベースに画像を生成します。
        image_bytes = params.get("image_bytes")
        # 将来的に image-to-image がサポートされた場合はここに組み込みます。

        config = types.GenerateImagesConfig(
            number_of_images=1,
            output_mime_type="image/png",
            aspect_ratio="1:1" if width == height else "16:9", # 近似のアスペクト比
            # negative_prompt の対応は API 次第
        )

        try:
            # generate_images は同期メソッドの場合と非同期メソッドの場合がある
            # 現在のSDKでは同期メソッドが主流のため run_in_executor を使用するか、直接呼び出す
            # ここでは asyncio にラップせず直接呼ぶ（SDKの仕様によってはブロッキングする可能性あり）
            import asyncio
            
            def _generate():
                return client.models.generate_images(
                    model='imagen-3.0-generate-001',
                    prompt=prompt,
                    config=config,
                )
            
            result = await asyncio.to_thread(_generate)
            
            if not result.generated_images:
                raise RuntimeError("No image generated by Gemini API.")
                
            generated_image = result.generated_images[0]
            
            out_bytes = generated_image.image.image_bytes
            
            return GenerationResult(
                image_bytes=out_bytes,
                width=width,
                height=height,
                metadata={"model": "imagen-3.0-generate-001"}
            )

        except Exception as e:
            raise RuntimeError(f"Gemini API generation failed: {e}")

    async def generate_multimodal(
        self,
        contents: list[dict],
        parameters: dict | None = None,
        api_key: str | None = None,
    ) -> GenerationResult:
        client = genai.Client(api_key=api_key) if api_key else self.client
        if not client:
            raise RuntimeError("GEMINI_API_KEY is not set.")

        import asyncio
        import base64

        formatted_contents = []
        for c in contents:
            parts = []
            for p in c.get("parts", []):
                if "text" in p and p["text"]:
                    parts.append(types.Part.from_text(text=p["text"]))
                elif "inline_data" in p and p["inline_data"]:
                    mime_type = p["inline_data"]["mime_type"]
                    data_b64 = p["inline_data"]["data"]
                    data_bytes = base64.b64decode(data_b64)
                    parts.append(types.Part.from_bytes(data=data_bytes, mime_type=mime_type))
            if parts:
                formatted_contents.append(types.Content(role="user", parts=parts))
        
        # Hypothetical future model for Interactions API image generation
        model_name = "gemini-3-pro-image" 
        
        try:
            def _generate():
                return client.models.generate_content(
                    model=model_name,
                    contents=formatted_contents,
                )
            
            result = await asyncio.to_thread(_generate)
            
            # Try to extract image from response parts
            if result.candidates and result.candidates[0].content.parts:
                for part in result.candidates[0].content.parts:
                    if hasattr(part, 'inline_data') and part.inline_data:
                        # Extract the first image we find
                        return GenerationResult(
                            image_bytes=part.inline_data.data,
                            width=1024,
                            height=1024,
                            metadata={"model": model_name}
                        )
            
            raise RuntimeError(f"No image returned by {model_name}.")
            
        except Exception as e:
            raise RuntimeError(f"Gemini API multimodal generation failed: {e}")
